version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 'echo "{ \"projects\": { \"default\": \"webrew\" } }" > .firebaserc'
      - run: 'echo "{ \"hosting\": { \"public\": \"./build/default\", \"rewrites\": [ { \"source\": \"**\", \"destination\": \"/index.html\" } ] } }" > firebase.json'

      - run: npm install
      
      - run: npm run polymer build
      - run: npm run firebase deploy -- --project "webrew" --token "$FIREBASE_TOKEN" --only "hosting" --debug